### PR TITLE
Experiment: retaining multiple errors across successive methods

### PR DESCRIPTION
**Pull request by peterbom**
Just an idea - would need to pull the new class out somewhere else

### CODE REVIEW

**Comment by theunrepentantgeek** [comment]
🤔 
When we talked about this in front of the whiteboard, we identified the UX workflow where we desire as many of the errors to be shown at once (so that users don't need to play whack-a-mole on errors).

But didn't we have that with the original form of this code?

**Comment by peterbom** [comment]
Yep, we did have that :)  I wasn't trying to change the behaviour at all; just trying out ways of chaining functions returning `Errorable`s so that errors could accumulate without having to manually build up the collection.

My earlier attempt used extension methods in `Common` for that, but as it's a technique that seems to go against the general design philosophy (i.e. the standard use of `Errorable` is that once you hit an error the value is discarded and no further 'success' operations are performed) I thought we agreed that'd be a bit confusing. As an alternative I just wanted to try an explicitly named class to allow similar (I thought slightly more intuitive) chaining of `Errorable`s without discarding the result on failure. That class needn't go in `Common` as it'd only be for UX purposes.

Was there something else I should have been looking into that came out of that whiteboard discussion?

**Comment by theunrepentantgeek** [comment]
You're right that the philosophy of `Errorable<T>` is that once you have any errors, things stop being triggered. In the case of the UX, the extra error messages we want to retain aren't generated from the `NodeEntitlements` or `ServerOptions` instances - they're generated by the command line parsing infrastructure. So, I don't think we actually need the instance to continue. 

I also suspect we don't need a separate class either - we already have all the tools to hand with the new `With()`, `Do()` and `Map()` extensions on `Errorable<T>`. 

I had a play with moving the various `ConfigureXYZ()` methods, changing them from local functions into extensions on `Errorable<T>`; in usage, they end up a little more clunky that what we had, but the flow of values is much cleaner. We retain the loose coupling of the existing methods (instead of giving them NodeEntitlement arguments), while also cleaning up the use of a separate list of errors. Check out https://github.com/Azure/azure-batch-software-entitlement/pull/79

Don't think there was anything extra to look into.

**Comment by peterbom** [comment]
Superseded by `Configure` methods on `ErrorableExtensions`

**Pull request closed without merging**
